   CREATE TABLE "DWUSER"."UPLOAD_TABLE" 
   (  "DATE_TIME" VARCHAR2(250 BYTE), 
  "POLLUTANT" VARCHAR2(250 BYTE), 
    "UNIT" VARCHAR2(250 BYTE), 
  "STATION" VARCHAR2(250 BYTE), 
    "INSTRUMENT" VARCHAR2(250 BYTE), 
  "AVERAGE" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FITWORLDGYM_STG" ;


  
    CREATE TABLE "DWUSER"."EVTB_HALIFAX_UPLOAD" 
   (	"DATE_TIME" TIMESTAMP (6), 
	"POLLUTANT" VARCHAR2(250 BYTE), 
	"UNIT" VARCHAR2(250 BYTE), 
	"STATION" VARCHAR2(250 BYTE), 
	"INSTRUMENT" VARCHAR2(250 BYTE), 
	"AVERAGE" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 5242880 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FITWORLDGYM_STG" ;
  
   CREATE TABLE "DWUSER"."EVTB_KENTVILLE_UPLOAD" 
   (	"DATE_TIME" TIMESTAMP (6), 
	"POLLUTANT" VARCHAR2(250 BYTE), 
	"UNIT" VARCHAR2(250 BYTE), 
	"STATION" VARCHAR2(250 BYTE), 
	"INSTRUMENT" VARCHAR2(250 BYTE), 
	"AVERAGE" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 524288 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FITWORLDGYM_STG" ;
  
    CREATE TABLE "DWUSER"."EVTB_LAKE_MAJOR_UPLOAD" 
   (	"DATE_TIME" TIMESTAMP (6), 
	"POLLUTANT" VARCHAR2(250 BYTE), 
	"UNIT" VARCHAR2(250 BYTE), 
	"STATION" VARCHAR2(250 BYTE), 
	"INSTRUMENT" VARCHAR2(250 BYTE), 
	"AVERAGE" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FITWORLDGYM_STG" ;
  
    CREATE TABLE "DWUSER"."EVTB_PICTOU_UPLOAD" 
   (	"DATE_TIME" TIMESTAMP (6), 
	"POLLUTANT" VARCHAR2(250 BYTE), 
	"UNIT" VARCHAR2(250 BYTE), 
	"STATION" VARCHAR2(250 BYTE), 
	"INSTRUMENT" VARCHAR2(250 BYTE), 
	"AVERAGE" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 6291456 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FITWORLDGYM_STG" ;
  
    CREATE TABLE "DWUSER"."EVTB_PORT_HAWK_UPLOAD" 
   (	"DATE_TIME" TIMESTAMP (6), 
	"POLLUTANT" VARCHAR2(250 BYTE), 
	"UNIT" VARCHAR2(250 BYTE), 
	"STATION" VARCHAR2(250 BYTE), 
	"INSTRUMENT" VARCHAR2(250 BYTE), 
	"AVERAGE" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 4194304 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FITWORLDGYM_STG" ;
  
  
  CREATE TABLE "DWUSER"."EVTB_SABLE_ISLAND_UPLOAD" 
   (	"DATE_TIME" TIMESTAMP (6), 
	"POLLUTANT" VARCHAR2(250 BYTE), 
	"UNIT" VARCHAR2(250 BYTE), 
	"STATION" VARCHAR2(250 BYTE), 
	"INSTRUMENT" VARCHAR2(250 BYTE), 
	"AVERAGE" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 4194304 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FITWORLDGYM_STG" ;
  
    CREATE TABLE "DWUSER"."EVTB_SYDNEY_UPLOAD" 
   (	"DATE_TIME" TIMESTAMP (6), 
	"POLLUTANT" VARCHAR2(250 BYTE), 
	"UNIT" VARCHAR2(250 BYTE), 
	"STATION" VARCHAR2(250 BYTE), 
	"INSTRUMENT" VARCHAR2(250 BYTE), 
	"AVERAGE" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 6291456 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FITWORLDGYM_STG" ;
  
    CREATE TABLE "DWUSER"."UPLOAD_TABLE" 
   (	"DATE_TIME" VARCHAR2(250 BYTE), 
	"POLLUTANT" VARCHAR2(250 BYTE), 
	"UNIT" VARCHAR2(250 BYTE), 
	"STATION" VARCHAR2(250 BYTE), 
	"INSTRUMENT" VARCHAR2(250 BYTE), 
	"AVERAGE" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 46137344 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FITWORLDGYM_STG" ;
  
    CREATE OR REPLACE FORCE VIEW "DWUSER"."EVVW_ALL" ("DATE_TIME", "POLLUTANT", "UNIT", "STATION", "INSTRUMENT", "AVERAGE") AS 
  SELECT "DATE_TIME","POLLUTANT","UNIT","STATION","INSTRUMENT","AVERAGE" FROM EVTB_AYLESFORD_UPLOAD
  UNION ALL
  SELECT "DATE_TIME","POLLUTANT","UNIT","STATION","INSTRUMENT","AVERAGE" FROM EVTB_HALIFAX_UPLOAD
  UNION ALL 
  SELECT "DATE_TIME","POLLUTANT","UNIT","STATION","INSTRUMENT","AVERAGE" FROM EVTB_LAKE_MAJOR_UPLOAD
  UNION ALL
  SELECT "DATE_TIME","POLLUTANT","UNIT","STATION","INSTRUMENT","AVERAGE" FROM EVTB_PICTOU_UPLOAD
  UNION ALL 
  SELECT "DATE_TIME","POLLUTANT","UNIT","STATION","INSTRUMENT","AVERAGE" FROM EVTB_PORT_HAWK_UPLOAD
  UNION ALL
  SELECT "DATE_TIME","POLLUTANT","UNIT","STATION","INSTRUMENT","AVERAGE" FROM EVTB_SABLE_ISLAND_UPLOAD
  UNION ALL
  SELECT "DATE_TIME","POLLUTANT","UNIT","STATION","INSTRUMENT","AVERAGE" FROM EVTB_SYDNEY_UPLOAD
  UNION ALL 
  SELECT "DATE_TIME","POLLUTANT","UNIT","STATION","INSTRUMENT","AVERAGE" FROM EVTB_KENTVILLE_UPLOAD;
