  CREATE TABLE "DWUSER"."EVTB_DIM_DATE" 
   (	"DATE_ID" VARCHAR2(250 BYTE), 
	"YEAR" VARCHAR2(250 BYTE), 
	"MONTH" VARCHAR2(250 BYTE), 
	"DAY" VARCHAR2(250 BYTE), 
	 CONSTRAINT "PK_DATE" PRIMARY KEY ("DATE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
    CREATE TABLE "DWUSER"."EVTB_DIM_INSTRUMENT" 
   (	"INSTRUMENT_ID" VARCHAR2(250 BYTE), 
	"STATION" VARCHAR2(250 BYTE), 
	"DESCRIPTION" VARCHAR2(250 BYTE), 
	 CONSTRAINT "PK_INSTRUMENT" PRIMARY KEY ("INSTRUMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
    CREATE TABLE "DWUSER"."EVTB_DIM_STATION" 
   (	"STATION_ID" VARCHAR2(250 BYTE), 
	"STATION" VARCHAR2(250 BYTE), 
	"DESCRIPTION" VARCHAR2(250 BYTE), 
	 CONSTRAINT "PK_STATION" PRIMARY KEY ("STATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
    CREATE TABLE "DWUSER"."EVTB_DIM_TIME" 
   (	"TIME_ID" VARCHAR2(250 BYTE), 
	"TIME_VAR" VARCHAR2(250 BYTE), 
	 CONSTRAINT "PK_TIME" PRIMARY KEY ("TIME_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
    CREATE TABLE "DWUSER"."EVTB_FACT" 
   (	"TIME_ID" VARCHAR2(250 BYTE), 
	"DATE_ID" VARCHAR2(250 BYTE), 
	"STATION_ID" VARCHAR2(250 BYTE), 
	"INSTRUMENT_ID" VARCHAR2(250 BYTE), 
	"AVERAGE" FLOAT(126), 
	"ID" VARCHAR2(250 BYTE), 
	 CONSTRAINT "PK_FACT" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE, 
	 CONSTRAINT "FK_DATE" FOREIGN KEY ("DATE_ID")
	  REFERENCES "DWUSER"."EVTB_DIM_DATE" ("DATE_ID") ENABLE, 
	 CONSTRAINT "FK_INSTRUEMT" FOREIGN KEY ("INSTRUMENT_ID")
	  REFERENCES "DWUSER"."EVTB_DIM_INSTRUMENT" ("INSTRUMENT_ID") ENABLE, 
	 CONSTRAINT "FK_STATION" FOREIGN KEY ("STATION_ID")
	  REFERENCES "DWUSER"."EVTB_DIM_STATION" ("STATION_ID") ENABLE, 
	 CONSTRAINT "FK_TIME" FOREIGN KEY ("TIME_ID")
	  REFERENCES "DWUSER"."EVTB_DIM_TIME" ("TIME_ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
  
    CREATE TABLE "DWUSER"."EVTB_HALIFAX_UPLOAD" 
   (	"DATE_TIME" TIMESTAMP (6), 
	"POLLUTANT" VARCHAR2(250 BYTE), 
	"UNIT" VARCHAR2(250 BYTE), 
	"STATION" VARCHAR2(250 BYTE), 
	"INSTRUMENT" VARCHAR2(250 BYTE), 
	"AVERAGE" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 5242880 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FITWORLDGYM_STG" ;
  
   CREATE TABLE "DWUSER"."EVTB_KENTVILLE_UPLOAD" 
   (	"DATE_TIME" TIMESTAMP (6), 
	"POLLUTANT" VARCHAR2(250 BYTE), 
	"UNIT" VARCHAR2(250 BYTE), 
	"STATION" VARCHAR2(250 BYTE), 
	"INSTRUMENT" VARCHAR2(250 BYTE), 
	"AVERAGE" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 524288 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FITWORLDGYM_STG" ;
  
    CREATE TABLE "DWUSER"."EVTB_LAKE_MAJOR_UPLOAD" 
   (	"DATE_TIME" TIMESTAMP (6), 
	"POLLUTANT" VARCHAR2(250 BYTE), 
	"UNIT" VARCHAR2(250 BYTE), 
	"STATION" VARCHAR2(250 BYTE), 
	"INSTRUMENT" VARCHAR2(250 BYTE), 
	"AVERAGE" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 8388608 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FITWORLDGYM_STG" ;
  
    CREATE TABLE "DWUSER"."EVTB_PICTOU_UPLOAD" 
   (	"DATE_TIME" TIMESTAMP (6), 
	"POLLUTANT" VARCHAR2(250 BYTE), 
	"UNIT" VARCHAR2(250 BYTE), 
	"STATION" VARCHAR2(250 BYTE), 
	"INSTRUMENT" VARCHAR2(250 BYTE), 
	"AVERAGE" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 6291456 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FITWORLDGYM_STG" ;
  
    CREATE TABLE "DWUSER"."EVTB_PORT_HAWK_UPLOAD" 
   (	"DATE_TIME" TIMESTAMP (6), 
	"POLLUTANT" VARCHAR2(250 BYTE), 
	"UNIT" VARCHAR2(250 BYTE), 
	"STATION" VARCHAR2(250 BYTE), 
	"INSTRUMENT" VARCHAR2(250 BYTE), 
	"AVERAGE" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 4194304 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FITWORLDGYM_STG" ;
  
  
  CREATE TABLE "DWUSER"."EVTB_SABLE_ISLAND_UPLOAD" 
   (	"DATE_TIME" TIMESTAMP (6), 
	"POLLUTANT" VARCHAR2(250 BYTE), 
	"UNIT" VARCHAR2(250 BYTE), 
	"STATION" VARCHAR2(250 BYTE), 
	"INSTRUMENT" VARCHAR2(250 BYTE), 
	"AVERAGE" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 4194304 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FITWORLDGYM_STG" ;
  
    CREATE TABLE "DWUSER"."EVTB_SYDNEY_UPLOAD" 
   (	"DATE_TIME" TIMESTAMP (6), 
	"POLLUTANT" VARCHAR2(250 BYTE), 
	"UNIT" VARCHAR2(250 BYTE), 
	"STATION" VARCHAR2(250 BYTE), 
	"INSTRUMENT" VARCHAR2(250 BYTE), 
	"AVERAGE" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 6291456 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FITWORLDGYM_STG" ;
  
    CREATE TABLE "DWUSER"."UPLOAD_TABLE" 
   (	"DATE_TIME" VARCHAR2(250 BYTE), 
	"POLLUTANT" VARCHAR2(250 BYTE), 
	"UNIT" VARCHAR2(250 BYTE), 
	"STATION" VARCHAR2(250 BYTE), 
	"INSTRUMENT" VARCHAR2(250 BYTE), 
	"AVERAGE" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 46137344 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FITWORLDGYM_STG" ;
  
    CREATE OR REPLACE FORCE VIEW "DWUSER"."EVVW_ALL" ("DATE_TIME", "POLLUTANT", "UNIT", "STATION", "INSTRUMENT", "AVERAGE") AS 
  SELECT "DATE_TIME","POLLUTANT","UNIT","STATION","INSTRUMENT","AVERAGE" FROM EVTB_AYLESFORD_UPLOAD
  UNION ALL
  SELECT "DATE_TIME","POLLUTANT","UNIT","STATION","INSTRUMENT","AVERAGE" FROM EVTB_HALIFAX_UPLOAD
  UNION ALL 
  SELECT "DATE_TIME","POLLUTANT","UNIT","STATION","INSTRUMENT","AVERAGE" FROM EVTB_LAKE_MAJOR_UPLOAD
  UNION ALL
  SELECT "DATE_TIME","POLLUTANT","UNIT","STATION","INSTRUMENT","AVERAGE" FROM EVTB_PICTOU_UPLOAD
  UNION ALL 
  SELECT "DATE_TIME","POLLUTANT","UNIT","STATION","INSTRUMENT","AVERAGE" FROM EVTB_PORT_HAWK_UPLOAD
  UNION ALL
  SELECT "DATE_TIME","POLLUTANT","UNIT","STATION","INSTRUMENT","AVERAGE" FROM EVTB_SABLE_ISLAND_UPLOAD
  UNION ALL
  SELECT "DATE_TIME","POLLUTANT","UNIT","STATION","INSTRUMENT","AVERAGE" FROM EVTB_SYDNEY_UPLOAD
  UNION ALL 
  SELECT "DATE_TIME","POLLUTANT","UNIT","STATION","INSTRUMENT","AVERAGE" FROM EVTB_KENTVILLE_UPLOAD;
