
 


 CREATE TABLE "DWUSER"."UPLOAD_TABLE" 
   (	"DATE_TIME" VARCHAR2(250 BYTE), 
	"POLLUTANT" VARCHAR2(250 BYTE), 
    "UNIT" VARCHAR2(250 BYTE), 
	"STATION" VARCHAR2(250 BYTE), 
    "INSTRUMENT" VARCHAR2(250 BYTE), 
	"AVERAGE" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FITWORLDGYM_STG" ;
  
 
  
  SELECT COUNT(1), STATION, INSTRUMENT FROM UPLOAD_TABLE
  GROUP BY STATION, INSTRUMENT ORDER BY STATION
  Date_Time	Pollutant	Unit	Station	Instrument	Average

  CREATE TABLE "DWUSER"."EVTB_AYLESFORD_UPLOAD" 
   (	"DATE_TIME" TIMESTAMP (6), 
	"POLLUTANT" VARCHAR2(250 BYTE), 
    "UNIT" VARCHAR2(250 BYTE),
	"STATION" VARCHAR2(250 BYTE), 
     "INSTRUMENT" VARCHAR2(250 BYTE),
	"AVERAGE" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FITWORLDGYM_STG" ;
  
    CREATE TABLE "DWUSER"."EVTB_HALIFAX_UPLOAD" 
   (	"DATE_TIME" TIMESTAMP (6), 
	"POLLUTANT" VARCHAR2(250 BYTE), 
    "UNIT" VARCHAR2(250 BYTE),
	"STATION" VARCHAR2(250 BYTE), 
     "INSTRUMENT" VARCHAR2(250 BYTE),
	"AVERAGE" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FITWORLDGYM_STG" ;
  
    CREATE TABLE "DWUSER"."EVTB_LAKE_MAJOR_UPLOAD" 
   (	"DATE_TIME" TIMESTAMP (6), 
	"POLLUTANT" VARCHAR2(250 BYTE), 
    "UNIT" VARCHAR2(250 BYTE),
	"STATION" VARCHAR2(250 BYTE), 
     "INSTRUMENT" VARCHAR2(250 BYTE),
	"AVERAGE" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FITWORLDGYM_STG" ;
  
    CREATE TABLE "DWUSER"."EVTB_PICTOU_UPLOAD" 
   (	"DATE_TIME" TIMESTAMP (6), 
	"POLLUTANT" VARCHAR2(250 BYTE), 
    "UNIT" VARCHAR2(250 BYTE),
	"STATION" VARCHAR2(250 BYTE), 
     "INSTRUMENT" VARCHAR2(250 BYTE),
	"AVERAGE" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FITWORLDGYM_STG" ;
  
    CREATE TABLE "DWUSER"."EVTB_PORT_HAWK_UPLOAD" 
   (	"DATE_TIME" TIMESTAMP (6), 
	"POLLUTANT" VARCHAR2(250 BYTE), 
    "UNIT" VARCHAR2(250 BYTE),
	"STATION" VARCHAR2(250 BYTE), 
     "INSTRUMENT" VARCHAR2(250 BYTE),
	"AVERAGE" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FITWORLDGYM_STG" ;
    CREATE TABLE "DWUSER"."EVTB_SABLE_ISLAND_UPLOAD" 
   (	"DATE_TIME" TIMESTAMP (6), 
	"POLLUTANT" VARCHAR2(250 BYTE), 
    "UNIT" VARCHAR2(250 BYTE),
	"STATION" VARCHAR2(250 BYTE), 
     "INSTRUMENT" VARCHAR2(250 BYTE),
	"AVERAGE" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FITWORLDGYM_STG" ;
    CREATE TABLE "DWUSER"."EVTB_SYDNEY_UPLOAD" 
   (	"DATE_TIME" TIMESTAMP (6), 
	"POLLUTANT" VARCHAR2(250 BYTE), 
    "UNIT" VARCHAR2(250 BYTE),
	"STATION" VARCHAR2(250 BYTE), 
     "INSTRUMENT" VARCHAR2(250 BYTE),
	"AVERAGE" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FITWORLDGYM_STG" ;
    CREATE TABLE "DWUSER"."EVTB_KENTVILLE_UPLOAD" 
   (	"DATE_TIME" TIMESTAMP (6), 
	"POLLUTANT" VARCHAR2(250 BYTE), 
    "UNIT" VARCHAR2(250 BYTE),
	"STATION" VARCHAR2(250 BYTE), 
     "INSTRUMENT" VARCHAR2(250 BYTE),
	"AVERAGE" FLOAT(126)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FITWORLDGYM_STG" ;
  
      CREATE TABLE "DWUSER"."EVCU_POLLUTION" 
   ( "REF_CODE" VARCHAR2(20 BYTE)	,
 "STATION" VARCHAR2(250 BYTE), 
   "INSTRUMENT" VARCHAR2(250 BYTE),
    "TIME_VARIANT" VARCHAR2(250 BYTE),
 "POLLUTANT" VARCHAR2(250 BYTE), 
    "UNIT" VARCHAR2(250 BYTE),
	"AVERAGE" FLOAT(126),
    "MAXIMUM" FLOAT(126),
      "MINIMUM" FLOAT(126),
        "STDEV" FLOAT(126)
    ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FITWORLDGYM_STG" ;
  -----------------------------------------------------
  select count(1) , station from upload_table
  group by station
  
  SELECT TO_TIMESTAMP(DATE_TIME,'MM-DD-YYYY HH:MI:SS PM'),A.*  --TO_DATE(SUBSTR(DATE_TIME,1,LENGTH(DATE_TIME)-3),'MM-DD-YYYY HH24:MI:SS'),A.* 
  FROM UPLOAD_TABLE A WHERE UPPER(STATION ) ='HALIFAX'
  AND SUBSTR(DATE_TIME,1,10) ='05/09/2006' and instrument ='TEOM'
  ORDER BY TO_TIMESTAMP(SUBSTR(DATE_TIME,1,LENGTH(DATE_TIME)-3),'MM-DD-YYYY HH12:MI:SS PM')
 
 
 INSERT INTO EVTB_HALIFAX_UPLOAD 
  SELECT TO_TIMESTAMP(DATE_TIME,'mm/dd/yyyy hh12:mi:ss am'), a.pollutant,a.unit,a.station, a.instrument,a.average FROM UPLOAD_TABLE a  
  WHERE UPPER(STATION ) ='HALIFAX'
  --AND SUBSTR(DATE_TIME,1,10) ='05/09/2006' and instrument ='TEOM' 
  order by date_time
  --sydney
   INSERT INTO EVTB_PICTOU_UPLOAD 
  SELECT TO_TIMESTAMP(DATE_TIME,'mm/dd/yyyy hh12:mi:ss am'), a.pollutant,a.unit,a.station, a.instrument,a.average FROM UPLOAD_TABLE a  
  WHERE UPPER(STATION ) ='PICTOU'
  --AND SUBSTR(DATE_TIME,1,10) ='05/09/2006' and instrument ='TEOM' 
  order by date_time
  COMMIT;
    INSERT INTO EVTB_PORT_HAWK_UPLOAD 
  SELECT TO_TIMESTAMP(DATE_TIME,'mm/dd/yyyy hh12:mi:ss am'), a.pollutant,a.unit,a.station, a.instrument,a.average FROM UPLOAD_TABLE a  
  WHERE UPPER(STATION ) ='PORT HAWKESBURY'
  --AND SUBSTR(DATE_TIME,1,10) ='05/09/2006' and instrument ='TEOM' 
  order by date_time;
  COMMIT;
  
     INSERT INTO EVTB_SABLE_ISLAND_UPLOAD 
  SELECT TO_TIMESTAMP(DATE_TIME,'mm/dd/yyyy hh12:mi:ss am'), a.pollutant,a.unit,a.station, a.instrument,a.average FROM UPLOAD_TABLE a  
  WHERE UPPER(STATION ) ='SABLE ISLAND'
  --AND SUBSTR(DATE_TIME,1,10) ='05/09/2006' and instrument ='TEOM' 
  order by date_time;
  COMMIT;
  
       INSERT INTO EVTB_KENTVILLE_UPLOAD 
  SELECT TO_TIMESTAMP(DATE_TIME,'mm/dd/yyyy hh12:mi:ss am'), a.pollutant,a.unit,a.station, a.instrument,a.average FROM UPLOAD_TABLE a  
  WHERE UPPER(STATION ) ='KENTVILLE'
  --AND SUBSTR(DATE_TIME,1,10) ='05/09/2006' and instrument ='TEOM' 
  order by date_time;
  COMMIT;
  
     INSERT INTO EVTB_AYLESFORD_UPLOAD 
  SELECT TO_TIMESTAMP(DATE_TIME,'mm/dd/yyyy hh12:mi:ss am'), a.pollutant,a.unit,a.station, a.instrument,a.average FROM UPLOAD_TABLE a  
  WHERE UPPER(STATION ) ='AYLESFORD'
  --AND SUBSTR(DATE_TIME,1,10) ='05/09/2006' and instrument ='TEOM' 
  order by date_time;
  COMMIT;
  
     INSERT INTO EVTB_LAKE_MAJOR_UPLOAD 
  SELECT TO_TIMESTAMP(DATE_TIME,'mm/dd/yyyy hh12:mi:ss am'), a.pollutant,a.unit,a.station, a.instrument,a.average FROM UPLOAD_TABLE a  
  WHERE UPPER(STATION ) ='LAKE MAJOR'
  --AND SUBSTR(DATE_TIME,1,10) ='05/09/2006' and instrument ='TEOM' 
  order by date_time;
  COMMIT;
  
  
  CREATE VIEW EVVW_ALL AS 
  SELECT * FROM EVTB_AYLESFORD_UPLOAD
  UNION ALL
  SELECT * FROM EVTB_HALIFAX_UPLOAD
  UNION ALL 
  SELECT * FROM EVTB_LAKE_MAJOR_UPLOAD
  UNION ALL
  SELECT * FROM EVTB_PICTOU_UPLOAD
  UNION ALL 
  SELECT * FROM EVTB_PORT_HAWK_UPLOAD
  UNION ALL
  SELECT * FROM EVTB_SABLE_ISLAND_UPLOAD
  UNION ALL
  SELECT * FROM EVTB_SYDNEY_UPLOAD
  UNION ALL 
  SELECT * FROM EVTB_KENTVILLE_UPLOAD
  
  SELECT  * FROM EVCU_POLLUTION
  INSERT INTO EVCU_POLLUTION
  SELECT 'YEAR' AS PP, STATION,INSTRUMENT,EXTRACT(YEAR FROM DATE_TIME),POLLUTANT,UNIT,MAX(AVERAGE),MIN(AVERAGE),AVG(AVERAGE),STDDEV(AVERAGE) 
  FROM EVVW_ALL A
  GROUP BY EXTRACT(YEAR FROM DATE_TIME), STATION,INSTRUMENT,POLLUTANT,UNIT
  ORDER BY EXTRACT(YEAR FROM DATE_TIME)


   CREATE TABLE "DWUSER"."EVTB_DIM_TIME" 
   (	"TIME_ID" VARCHAR2 (250 BYTE) CONSTRAINT  PK_TIME PRIMARY KEY , 
	"TIME_VAR" VARCHAR2(250 BYTE)
   )
 ;
 
  CREATE TABLE "DWUSER"."EVTB_DIM_INSTRUMENT" 
   (	"INSTRUMENT_ID" VARCHAR2 (250 BYTE) CONSTRAINT  PK_INSTRUMENT PRIMARY KEY , 
	"STATION" VARCHAR2(250 BYTE) ,"DESCRIPTION" VARCHAR2(250 BYTE)
   )
 ;
  
  

 

  

  
  
  
  

  
  